// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 8);
user_pref("app.normandy.startupRolloutPrefs.network.cookie.cookieBehavior", 4);
user_pref("app.normandy.user_id", "3be30f81-95cd-4a15-bdc6-e9b04961d260");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1578574666);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1578574786);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1578577786);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1578574426);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1578574306);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1578574546);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1578574965);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1578574935);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 154071);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1578574159);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 87);
user_pref("browser.newtabpage.activity-stream.impressionId", "{c0e60508-8248-4c0b-8d5f-47b0fe431944}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.rights.3.shown", true);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1578577839487");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1578579623487");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1578577776972");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1578581376972");
user_pref("browser.search.region", "CL");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1578574910");
user_pref("browser.slowStartup.averageTime", 19391);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20191205184924");
user_pref("browser.startup.homepage_override.mstone", "71.0");
user_pref("browser.startup.lastColdStartupCheck", 1578574909);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1578574168484");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "71.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "a96ecba85ba04f6ba855fc6f91189d09");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.lastModified", "Wed, 08 Jan 2020 23:38:05 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.cache.lastUpdate", 1578574667);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "71.0");
user_pref("extensions.lastPlatformVersion", "71.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"bf2cac87-094a-49da-8c0d-8f37d3e1384a\",\"fxmonitor@mozilla.org\":\"9f9835eb-ea53-454a-bd74-a4be631c8531\",\"screenshots@mozilla.org\":\"91a1b60d-379a-4906-8dad-c72468ac8dde\",\"webcompat-reporter@mozilla.org\":\"ef365029-ba58-4d9d-a603-ea42fce7f170\",\"webcompat@mozilla.org\":\"dbd369c9-c920-4276-8008-134dc2c7f998\",\"default-theme@mozilla.org\":\"c198a5a5-006d-4396-85ed-010f0992a0a7\",\"google@search.mozilla.org\":\"a4a061be-2f16-43ee-ab2c-95b5d2b0cbc1\",\"amazondotcom@search.mozilla.org\":\"1d3e9a03-281e-4cd8-9d27-9db8dfde5f7f\",\"bing@search.mozilla.org\":\"6893af69-3a1a-48bf-9654-1ceb59bc73ca\",\"ddg@search.mozilla.org\":\"36b91f9a-62bd-4168-b9e2-1831c8c05f96\",\"ebay@search.mozilla.org\":\"0dce768f-db26-457a-b4ce-15543300edc1\",\"twitter@search.mozilla.org\":\"dc401596-2b1e-459a-ac05-5025b52516de\",\"wikipedia@search.mozilla.org\":\"69b67145-adf1-41a7-97f8-23c57911799a\",\"drae@search.mozilla.org\":\"bf6168e7-81ba-4687-ac43-f5a650ca143a\",\"mercadolibre@search.mozilla.org\":\"83b2cb72-0a6f-4b9e-8d67-964f180e29f7\"}");
user_pref("font.internaluseonly.changed", true);
user_pref("idle.lastDailyNotification", 1578574714);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1578574932);
user_pref("media.gmp-gmpopenh264.version", "1.8.1.1");
user_pref("media.gmp-manager.buildID", "20191205184924");
user_pref("media.gmp-manager.lastCheck", 1578574929);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("permissions.eventTelemetry.salt", "{565aaf0b-f88c-47de-8186-a0163270df55}");
user_pref("places.database.lastMaintenance", 1578574715);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "547768a0-c099-44d3-9687-6d49f01a9919");
user_pref("security.sandbox.plugin.tempDirSuffix", "abf311e9-6a14-47b8-83f1-a5aa75dfed4d");
user_pref("services.blocklist.pinning.checked", 1578574838);
user_pref("services.settings.clock_skew_seconds", -292);
user_pref("services.settings.last_etag", "\"1578526685310\"");
user_pref("services.settings.last_update_seconds", 1578574838);
user_pref("services.settings.main.cfr-fxa.last_check", 1578574838);
user_pref("services.settings.main.cfr.last_check", 1578574838);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1578574838);
user_pref("services.settings.main.hijack-blocklists.last_check", 1578574838);
user_pref("services.settings.main.language-dictionaries.last_check", 1578574838);
user_pref("services.settings.main.normandy-recipes.last_check", 1578574838);
user_pref("services.settings.main.sites-classification.last_check", 1578574838);
user_pref("services.settings.main.tippytop.last_check", 1578574838);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1578574838);
user_pref("services.settings.security.onecrl.checked", 1578574838);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1578574715);
user_pref("toolkit.startup.last_success", 1578574898);
user_pref("toolkit.telemetry.cachedClientID", "d60964a1-4e47-4320-8c19-5440c7cec5cf");
user_pref("toolkit.telemetry.previousBuildID", "20191205184924");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.extendedTriplets.experiment", "control");
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
