// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1578578655);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.cache.disk.amount_written", 4);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.search.region", "CL");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "68.2.2");
user_pref("extensions.lastPlatformVersion", "68.3.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"wetransfer@extensions.thunderbird.net\":\"b9b26224-21fd-40c1-951a-e142f679449b\",\"default-theme@mozilla.org\":\"83d04a79-83f8-4706-8c24-95cf73ce1c42\",\"google@search.mozilla.org\":\"e2f8803a-d0ff-4318-b268-060bc8c2c501\",\"bing@search.mozilla.org\":\"68cf6fef-2e92-430e-a527-ee4de3068aa3\",\"drae@search.mozilla.org\":\"95b1baed-92f0-4fcc-8ae3-395cf1c725d8\",\"ddg@search.mozilla.org\":\"98344089-d11d-4879-aec7-74d7aa0779b4\",\"twitter@search.mozilla.org\":\"03faa6c2-0512-430e-8252-05495a492eff\",\"wikipedia@search.mozilla.org\":\"9adf81e1-7862-4ab2-939b-34a5218a6646\"}");
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.append_preconfig_smtpservers.version", 2);
user_pref("mail.default_charsets.migrated", 1);
user_pref("mail.folder.views.version", 1);
user_pref("mail.openMessageBehavior.version", 1);
user_pref("mail.spam.version", 1);
user_pref("mail.ui-rdf.version", 17);
user_pref("mailnews.database.global.datastore.id", "d92fd7ea-325c-4b6f-a6c7-46e03da261e");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "68.2.2");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Importante");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Trabajo");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "Por hacer");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Más tarde");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("security.sandbox.plugin.tempDirSuffix", "0b36a6fc-0d75-4a39-87d0-8fdc162bb54e");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.telemetry.prompted", 2);
